CREATE USER 'user_db_user'@'%' IDENTIFIED BY 'password';
REVOKE ALL PRIVILEGES ON *.* FROM 'user_db_user'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'user_db_user'@'%';
ALTER USER 'user_db_user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;